import json
import logging
from typing import Optional, List
from app.core.config import settings
from app.schemas.ai import (
    TriageRequest,
    TriageResponse,
    DifferentialDiagnosisItem,
    SOAPGenerateRequest,
    SOAPGenerateResponse,
    VitalsInput,
)

logger = logging.getLogger("clinova.ai")


class GeminiClinicalService:
    def __init__(self):
        self.api_key = settings.GEMINI_API_KEY
        self.client = None
        if not settings.OFFLINE_DEMO and self.api_key and self.api_key.strip():
            try:
                from google import genai
                self.client = genai.Client(api_key=self.api_key)
                logger.info("Google GenAI client initialized with configured API key.")
            except Exception as e:
                logger.warning(f"Could not initialize GenAI Client: {e}. Falling back to clinical rules.")

    async def analyze_triage(self, req: TriageRequest) -> TriageResponse:
        """Perform AI-assisted clinical triage and differential diagnosis."""
        if self.client:
            try:
                return await self._call_gemini_triage(req)
            except Exception as e:
                logger.error(f"Gemini API call failed: {e}. Falling back to clinical rule engine.", exc_info=True)
                return self._heuristic_triage(req, note=f"Fallback active: {e}")
        
        return self._heuristic_triage(req)

    async def generate_soap_notes(self, req: SOAPGenerateRequest) -> SOAPGenerateResponse:
        """Synthesize clinical encounter notes into formatted SOAP notes."""
        if self.client:
            try:
                return await self._call_gemini_soap(req)
            except Exception as e:
                logger.error(f"Gemini API call failed: {e}. Falling back to clinical rule engine.", exc_info=True)
                return self._heuristic_soap(req, note=f"Fallback active: {e}")

        return self._heuristic_soap(req)

    async def _call_gemini_triage(self, req: TriageRequest) -> TriageResponse:
        from google.genai import types

        prompt = f"""
You are CLINOVA AI, an expert clinical decision support copilot for healthcare providers.
Analyze the following patient clinical presentation:

Chief Complaint: {req.chief_complaint}
Reported Symptoms: {', '.join(req.symptoms)}
Duration: {req.symptom_duration or 'Unspecified'}
Patient Age: {req.age or 'Unspecified'}, Gender: {req.gender or 'Unspecified'}
Relevant Medical History: {req.relevant_medical_history or 'None reported'}
Known Allergies: {req.known_allergies or 'None reported'}
Vitals: {req.vitals.model_dump_json() if req.vitals else 'No vitals recorded'}

TASK:
1. Determine Triage Urgency Level: Must be strictly one of ["CRITICAL", "URGENT", "ROUTINE", "LOW"].
2. Identify any Immediate Emergency Red Flags.
3. Formulate Top 3 Differential Diagnoses with Probability ("High", "Moderate", "Low"), Clinical Rationale, and Recommended Workup.
4. Recommend Immediate Clinical Bedside Actions and Suggested Monitoring.
5. Provide concise Clinical Reasoning.

Respond strictly in valid JSON matching this schema:
{{
  "urgency_level": "CRITICAL" | "URGENT" | "ROUTINE" | "LOW",
  "urgency_color": "Rose" | "Amber" | "Teal" | "Slate",
  "emergency_red_flags": ["string"],
  "differential_diagnoses": [
    {{
      "condition": "string",
      "probability": "High" | "Moderate" | "Low",
      "rationale": "string",
      "recommended_workup": ["string"]
    }}
  ],
  "immediate_actions": ["string"],
  "clinical_reasoning": "string",
  "suggested_monitoring": ["string"]
}}
"""
        response = self.client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                temperature=0.2,
            ),
        )

        data = json.loads(response.text)
        return TriageResponse(
            urgency_level=data.get("urgency_level", "URGENT"),
            urgency_color=data.get("urgency_color", "Amber"),
            emergency_red_flags=data.get("emergency_red_flags", []),
            differential_diagnoses=[
                DifferentialDiagnosisItem(**item) for item in data.get("differential_diagnoses", [])
            ],
            immediate_actions=data.get("immediate_actions", []),
            clinical_reasoning=data.get("clinical_reasoning", "Generated by Gemini Clinical Intelligence."),
            suggested_monitoring=data.get("suggested_monitoring", []),
            source="Gemini 2.5 Flash Clinical Engine",
        )

    async def _call_gemini_soap(self, req: SOAPGenerateRequest) -> SOAPGenerateResponse:
        from google.genai import types

        prompt = f"""
You are CLINOVA AI, a medical documentation copilot. Synthesize the following encounter information into high-quality clinical SOAP notes:

Patient: {req.patient_name} ({req.age_and_gender or 'Demographics unspecified'})
Chief Complaint: {req.chief_complaint}
Clinical Encounter Transcript / Notes:
{req.encounter_notes}
Vitals: {req.vitals.model_dump_json() if req.vitals else 'Not recorded'}
History: {req.medical_history or 'None'}

Provide structured JSON with:
{{
  "subjective": "Detailed history of present illness and patient reported symptoms",
  "objective": "Objective findings including vitals and physical exam observations",
  "assessment": "Clinical synthesis, primary impression, and differential diagnosis",
  "plan": "Diagnostic plan, therapeutic interventions, medications, and follow-up",
  "patient_friendly_summary": "Plain English, jargon-free summary for the patient"
}}
"""
        response = self.client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                temperature=0.2,
            ),
        )

        data = json.loads(response.text)
        return SOAPGenerateResponse(
            subjective=data.get("subjective", ""),
            objective=data.get("objective", ""),
            assessment=data.get("assessment", ""),
            plan=data.get("plan", ""),
            patient_friendly_summary=data.get("patient_friendly_summary", ""),
        )

    def _heuristic_triage(self, req: TriageRequest, note: str = "") -> TriageResponse:
        """Deterministic, rule-based medical triage heuristic for development and offline testing."""
        symptoms_str = " ".join(req.symptoms).lower() + " " + req.chief_complaint.lower()
        vitals: Optional[VitalsInput] = req.vitals

        is_critical = False
        is_urgent = False
        red_flags: List[str] = []
        differentials: List[DifferentialDiagnosisItem] = []
        immediate_actions: List[str] = []

        # 1. Critical Vital Signs / Symptom Checks
        if vitals and vitals.oxygen_saturation and vitals.oxygen_saturation < 90.0:
            is_critical = True
            red_flags.append(f"Severe Hypoxemia: SpO2 {vitals.oxygen_saturation}% is critically low (<90%)")
        if vitals and vitals.blood_pressure_systolic and (vitals.blood_pressure_systolic > 190 or vitals.blood_pressure_systolic < 85):
            is_critical = True
            red_flags.append(f"Hemodynamic Instability: Systolic BP {vitals.blood_pressure_systolic} mmHg is outside safe physiological range")
        if vitals and vitals.heart_rate and (vitals.heart_rate > 140 or vitals.heart_rate < 40):
            is_critical = True
            red_flags.append(f"Severe Arrhythmia Risk: Heart rate {vitals.heart_rate} BPM")

        # 2. Symptom Pattern Matching
        if any(w in symptoms_str for w in ["chest pain", "angina", "cardiac", "pressure in chest", "left arm pain"]):
            if any(w in symptoms_str for w in ["radiat", "sweat", "diaphoresis", "shortness of breath", "nausea"]):
                is_critical = True
                red_flags.append("High suspicion of Acute Coronary Syndrome (ACS / STEMI)")
            else:
                is_urgent = True

            differentials.append(
                DifferentialDiagnosisItem(
                    condition="Acute Coronary Syndrome (ACS / Unstable Angina)",
                    probability="High" if is_critical else "Moderate",
                    rationale="Chest pain presentation with associated systemic symptoms warrants immediate cardiac exclusion.",
                    recommended_workup=["12-lead ECG within 10 mins", "Serial High-Sensitivity Troponin", "Chest X-Ray", "Echocardiogram"],
                )
            )
            differentials.append(
                DifferentialDiagnosisItem(
                    condition="Gastroesophageal Reflux Disease (GERD) / Esophageal Spasm",
                    probability="Low",
                    rationale="Secondary non-ischemic differential, diagnosis of exclusion once cardiac etiology is ruled out.",
                    recommended_workup=["Trial of antacids post-cardiac clearance"],
                )
            )
            immediate_actions.extend(["Acquire 12-lead ECG immediately", "Establish IV access", "Administer Aspirin 325mg if not contraindicated", "Continuous cardiac telemetry"])

        elif any(w in symptoms_str for w in ["shortness of breath", "dyspnea", "wheezing", "asthma", "stridor"]):
            is_urgent = True
            differentials.append(
                DifferentialDiagnosisItem(
                    condition="Acute Exacerbation of Asthma / COPD",
                    probability="High",
                    rationale="Respiratory distress with wheezing and tachypnea.",
                    recommended_workup=["Peak Expiratory Flow", "Chest X-Ray", "Arterial Blood Gas (ABG)"],
                )
            )
            differentials.append(
                DifferentialDiagnosisItem(
                    condition="Pulmonary Embolism (PE)",
                    probability="Moderate",
                    rationale="Must consider in any sudden-onset acute dyspnea.",
                    recommended_workup=["D-dimer assay", "Wells Score evaluation", "CT Pulmonary Angiogram"],
                )
            )
            immediate_actions.extend(["Supplemental oxygen via nasal cannula to target SpO2 > 94%", "Inhaled bronchodilators (Albuterol/Ipratropium)", "Elevate head of bed to 45 degrees"])

        elif any(w in symptoms_str for w in ["fever", "chills", "infection", "sepsis", "cough", "sputum"]):
            differentials.append(
                DifferentialDiagnosisItem(
                    condition="Community-Acquired Pneumonia (CAP)",
                    probability="High",
                    rationale="Febrile respiratory syndrome with productive cough.",
                    recommended_workup=["CBC with differential", "Chest Radiograph (PA/Lateral)", "Blood cultures x 2 prior to antibiotics"],
                )
            )
            differentials.append(
                DifferentialDiagnosisItem(
                    condition="Viral Upper Respiratory Tract Infection (URTI) / Influenza",
                    probability="Moderate",
                    rationale="Viral prodrome common during seasonal surges.",
                    recommended_workup=["Multiplex respiratory viral PCR panel"],
                )
            )
            immediate_actions.extend(["Antipyretic therapy (Acetaminophen 650mg)", "Oral or IV rehydration", "Monitor temperature curve and work of breathing"])

        else:
            differentials.append(
                DifferentialDiagnosisItem(
                    condition="Nonspecific Clinical Presentation",
                    probability="Moderate",
                    rationale="Symptoms require formal history and physical examination by attending clinician.",
                    recommended_workup=["Complete Blood Count (CBC)", "Comprehensive Metabolic Panel (CMP)", "Focused physical examination"],
                )
            )
            immediate_actions.append("Schedule physician consultation for comprehensive clinical assessment.")

        # Determine urgency classification
        if is_critical:
            urgency_level = "CRITICAL"
            urgency_color = "Rose"
        elif is_urgent:
            urgency_level = "URGENT"
            urgency_color = "Amber"
        elif any(w in symptoms_str for w in ["fever", "pain", "swelling", "vomiting"]):
            urgency_level = "ROUTINE"
            urgency_color = "Teal"
        else:
            urgency_level = "LOW"
            urgency_color = "Slate"

        reasoning = (
            f"Rule-based clinical triage engine evaluated chief complaint '{req.chief_complaint}' and {len(req.symptoms)} "
            f"reported symptoms against emergency physiological thresholds. "
            f"{f'Note: {note}' if note else 'Ready for live Gemini AI inference upon configuring GEMINI_API_KEY in .env.'}"
        )

        return TriageResponse(
            urgency_level=urgency_level,
            urgency_color=urgency_color,
            emergency_red_flags=red_flags,
            differential_diagnoses=differentials,
            immediate_actions=immediate_actions,
            clinical_reasoning=reasoning,
            suggested_monitoring=["Continuous Pulse Oximetry", "Hourly Blood Pressure", "Pain score reassessment"],
            source="CLINOVA AI Clinical Decision Engine (Deterministic Heuristic)",
        )

    def _heuristic_soap(self, req: SOAPGenerateRequest, note: str = "") -> SOAPGenerateResponse:
        """Deterministic clinical SOAP note generator."""
        vitals_str = req.vitals.model_dump_json() if req.vitals else "Not recorded"
        return SOAPGenerateResponse(
            subjective=(
                f"PATIENT: {req.patient_name}\n"
                f"CHIEF COMPLAINT: {req.chief_complaint}\n"
                f"HISTORY OF PRESENT ILLNESS:\n{req.encounter_notes}\n"
                f"PAST MEDICAL HISTORY: {req.medical_history or 'Non-contributory'}"
            ),
            objective=(
                f"VITALS: {vitals_str}\n"
                "PHYSICAL EXAM: Alert, oriented x 3, in no acute distress unless noted in triage. "
                "Cardiovascular: Regular rate and rhythm. Respiratory: Clear to auscultation bilaterally. "
                "Abdomen: Soft, non-tender, non-distended."
            ),
            assessment=(
                f"PRIMARY IMPRESSION: Clinical presentation consistent with evaluation for {req.chief_complaint}.\n"
                "DIFFERENTIAL: Evaluated based on clinical presentation and bedside findings."
            ),
            plan=(
                "1. Confirm baseline laboratory and diagnostic studies as indicated.\n"
                "2. Symptomatic medical management and monitoring.\n"
                "3. Patient education regarding red flag symptoms requiring immediate emergency care.\n"
                "4. Follow-up with primary care clinician in 3-5 days or sooner if symptoms worsen."
            ),
            patient_friendly_summary=(
                f"You were evaluated today for {req.chief_complaint}. Your healthcare provider has reviewed your symptoms "
                "and created a treatment plan. Please follow the instructions provided, take any prescribed medications "
                "as directed, and seek immediate emergency care if you experience worsening symptoms or difficulty breathing."
            ),
        )

    async def synthesize_triage_note(
        self,
        case_id: str,
        symptoms: str,
        speech_transcript: Optional[str] = None,
        report_fields: Optional[List] = None,
        patient_age: Optional[int] = None,
        gender: Optional[str] = None,
        facility_type: str = "Government Hospital",
        visit_type: str = "Outpatient",
    ) -> dict:
        """Synthesizes a strictly non-diagnostic structured reviewer triage note."""
        from app.services.risk_engine import risk_engine

        combined_text = f"{symptoms} {speech_transcript or ''}"
        signals, queue_cat, queue_reason = risk_engine.evaluate(combined_text)

        # 1. Timeline construction
        timeline = [
            {"day": "Day 1", "description": "Patient notes onset of primary discomfort and initial symptoms.", "source": "Patient history"},
            {"day": "Day 2", "description": "Symptoms persist; patient notes worsening discomfort.", "source": "Patient history"},
            {"day": "Day 3 (Today)", "description": f"Presenting to {facility_type} for clinical intake: {symptoms[:120]}...", "source": "Current intake"},
        ]

        # 2. Missing information detection & follow-up questions
        missing_info = []
        follow_up = []

        lower_s = symptoms.lower()
        if not any(w in lower_s for w in ["day", "week", "month", "hour", "yesterday", "since"]):
            missing_info.append("Precise onset and progression timeframe")
            follow_up.append("When exactly did these symptoms first begin?")

        if not any(w in lower_s for w in ["mild", "moderate", "severe", "intense", "sharp", "dull"]):
            missing_info.append("Subjective symptom severity score (1-10)")
            follow_up.append("On a scale of 1 to 10, how severe is the primary discomfort right now?")

        missing_info.append("Current daily prescription or over-the-counter medications")
        follow_up.append("Is the patient currently taking any daily medicines or home remedies?")

        if not report_fields:
            missing_info.append("Prior diagnostic laboratory or imaging records")
            follow_up.append("Are there any previous blood tests or clinic prescriptions available for review?")

        # 3. Chief concern and symptom summary
        chief_concern = symptoms.split(",")[0].split(".")[0].strip() or "Symptom intake"
        summary = (
            f"Patient ({patient_age or 'adult'}yo {gender or 'patient'}) presenting for {visit_type} "
            f"at {facility_type}. Reported symptoms: {symptoms}. "
            f"{'Voice transcript captured. ' if speech_transcript else ''}"
            f"{f'{len(report_fields)} laboratory parameters extracted via OCR. ' if report_fields else ''}"
            "Organized for qualified medical officer evaluation."
        )

        sources = ["Patient direct input"]
        if speech_transcript:
            sources.append("Voice intake (speech-to-text)")
        if report_fields:
            sources.append("Sample report OCR extraction")
        sources.append("Deterministic risk rules (TRIAGE-R01 - R06)")

        return {
            "case_id": case_id,
            "chief_concern": chief_concern,
            "symptom_summary": summary,
            "timeline": timeline,
            "reported_symptoms": [s.strip() for s in symptoms.split(",") if s.strip()][:5],
            "relevant_history": ["Requires confirmation by reviewing clinician during clinical encounter"],
            "extracted_report_data": [f.model_dump() if hasattr(f, 'model_dump') else f for f in (report_fields or [])],
            "visual_inputs": [],
            "missing_information": missing_info,
            "follow_up_questions": follow_up,
            "risk_signals": [s.model_dump() if hasattr(s, 'model_dump') else s for s in signals],
            "queue_category": queue_cat,
            "queue_reason": queue_reason,
            "sources": sources,
            "ai_generated": True,
            "requires_human_review": True,
            "is_diagnostic": False,
            "disclaimer": (
                "Educational prototype and triage-support purposes only. "
                "This system does not diagnose, prescribe treatment, or replace a qualified healthcare professional. "
                "All AI-generated information requires human review."
            ),
        }



ai_service = GeminiClinicalService()